/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Catering_Mgnt_Sys;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
/**
 *
 * @author Varun M G
 */
public class Catering_Mgnt_Sys extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String password = "Varun@21";
    private static final String dataConn = "jdbc:mysql://localhost:3306/connector1";
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int i,q,id,deleteItem;
    
    public Catering_Mgnt_Sys() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //=================================================FUNCTION==========================================================
    
    public void upDateDB()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement("select * from connector1");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next())
            {
                Vector columnData = new Vector();
                
                for(i=1;i<=q;i++)
                {
                    columnData.add(rs.getString("id"));
                    columnData.add(rs.getString("CustID"));
                    columnData.add(rs.getString("Name"));
                    columnData.add(rs.getString("Phone"));
                    columnData.add(rs.getString("Event"));
                    columnData.add(rs.getString("Date"));
                    columnData.add(rs.getString("Food"));
                    columnData.add(rs.getString("Item"));
                    columnData.add(rs.getString("Address"));
                    columnData.add(rs.getString("Quantity"));
                    columnData.add(rs.getString("Total"));
                }
                RecordTable.addRow(columnData);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    
    
    //=================================================END FUNCTION==========================================================
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtCid = new javax.swing.JTextField();
        jtxtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtPhone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtEname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtFood = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtIno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jtxtQuantity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jlabel7 = new javax.swing.JLabel();
        jtxtaddr = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jBtnSearch = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jtxtSid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jbtnMenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtnPrint = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Customer ID");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jtxtCid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCidActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtCid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 490, -1));

        jtxtName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 490, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Name");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jtxtPhone.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(jtxtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 490, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Phone Number");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jtxtEname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(jtxtEname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 490, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Food ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jtxtDate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(jtxtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 490, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Item number");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jtxtFood.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(jtxtFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 490, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Quantity");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        jtxtIno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(jtxtIno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 490, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Event Name");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CustID", "Name", "Phone", "Event", "Date", "Food", "Item", "Address", "Quantity", "Total"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 700, 100));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Event Date");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jtxtQuantity.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(jtxtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 230, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Total");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, -1, -1));

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 160, -1));

        jlabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlabel7.setText("Address");
        jPanel3.add(jlabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jtxtaddr.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(jtxtaddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 490, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 740, 640));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("CATERING MANAGEMENT SYSTEM");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1160, 70));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnSearch.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnSearch.setText("SEARCH");
        jBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("ID");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jtxtSid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel5.add(jtxtSid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 100, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("F:\\catering images and stuff\\Untitled design (4).png")); // NOI18N
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 180, 180));

        jbtnMenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnMenu.setText("MENU");
        jbtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenuActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 100, 200, 640));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPrint.setText("PRINT");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 140, 50));

        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnUpdate.setText("UPDATE");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 140, 50));

        jbtnAdd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnAdd.setText("ADD");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 140, 50));

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnReset.setText("RESET");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 140, 50));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnExit.setText("EXIT");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 140, 50));

        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDelete.setText("DELETE");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 140, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 200, 640));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1200, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement("insert into connector1(CustID,Name,Phone,Event,Date,"
                    +"Food,Item,Address,Quantity,Total)value(?,?,?,?,?,?,?,?,?,?)");
            
            pst.setString(1, jtxtCid.getText());
            pst.setString(2, jtxtName.getText());
            pst.setString(3, jtxtPhone.getText());
            pst.setString(4, jtxtEname.getText());
            pst.setString(5, jtxtDate.getText());
            pst.setString(6, jtxtFood.getText());
            pst.setString(7, jtxtIno.getText());
            pst.setString(8, jtxtaddr.getText());
            pst.setString(9, jtxtQuantity.getText());
            pst.setString(10, jtxtTotal.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added Successfully!!");
            upDateDB();
        }
        catch(ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Catering_Mgnt_Sys.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(SQLException ex)
        {
            java.util.logging.Logger.getLogger(Catering_Mgnt_Sys.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNameActionPerformed
//EXIT FUNCTION
    private JFrame frame;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        jtxtCid.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        jtxtName.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        jtxtPhone.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        jtxtEname.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
        jtxtDate.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
        jtxtFood.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
        jtxtIno.setText(RecordTable.getValueAt(SelectedRows, 7).toString());
        jtxtaddr.setText(RecordTable.getValueAt(SelectedRows, 8).toString());
        jtxtQuantity.setText(RecordTable.getValueAt(SelectedRows, 9).toString());
        jtxtTotal.setText(RecordTable.getValueAt(SelectedRows, 10).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jtxtCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCidActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Do you want to EXIT the Application","CATERING MANAGEMENT SYSTEM",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();

        try
        {
            id = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());

            deleteItem = JOptionPane.showConfirmDialog(null,"Do you want to delete this data ","Warning",JOptionPane.YES_NO_OPTION);
            if(deleteItem == JOptionPane.YES_NO_OPTION)
            {
                Class.forName("com.mysql.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConn,username,password);
                pst = sqlConn.prepareStatement("delete from connector1 where id =?");

                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Deleted Successfully");
                upDateDB();
                jtxtCid.setText("");
                jtxtName.setText("");
                jtxtPhone.setText("");
                jtxtEname.setText("");
                jtxtDate.setText("");
                jtxtFood.setText("");
                jtxtIno.setText("");
                jtxtaddr.setText("");
                jtxtQuantity.setText("");
                jtxtTotal.setText("");
                
            }
        }
        catch(ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Catering_Mgnt_Sys.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(SQLException ex)
        {
            System.err.println(ex);
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jtxtCid.setText("");
        jtxtName.setText("");
        jtxtPhone.setText("");
        jtxtEname.setText("");
        jtxtDate.setText("");
        jtxtFood.setText("");
        jtxtIno.setText("");
        jtxtaddr.setText("");
        jtxtQuantity.setText("");
        jtxtTotal.setText("");
        
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        RecordTable.setRowCount(0);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        MessageFormat header = new MessageFormat("Printing in Progress");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");

        try
        {
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("No printer found", e.getMessage());
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            int row = jTable1.getSelectedRow();
            String value = (jTable1.getModel().getValueAt(row, 0).toString());
            pst = sqlConn.prepareStatement("update connector1 set CustID=?,Name=?,Phone=?,Event=?,Date=?,"
                +"Food=?,Item=?,Address=?,Quantity=?,Total=? where id="+value);

            pst.setString(1, jtxtCid.getText());
            pst.setString(2, jtxtName.getText());
            pst.setString(3, jtxtPhone.getText());
            pst.setString(4, jtxtEname.getText());
            pst.setString(5, jtxtDate.getText());
            pst.setString(6, jtxtFood.getText());
            pst.setString(7, jtxtIno.getText());
            pst.setString(8, jtxtaddr.getText());
            pst.setString(9, jtxtQuantity.getText());
            pst.setString(10, jtxtTotal.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Updated Successfully!!");
            upDateDB();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchActionPerformed
        String Sid = jtxtSid.getText();
        String sql = "select * from connector1 where CustID = '"+Sid+"'";
        jtxtSid.setText("");
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement(sql);
            rs = pst.executeQuery();
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.getRowCount();
            if(rs.next())
            {
                JOptionPane.showMessageDialog(null, "Customer's Data Exists");
                do
                {
                    RecordTable.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),
                        rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11)});
                }while(rs.next());
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Customer's Data does not exists");
            }
        }
         catch(Exception ex)
         {
             JOptionPane.showMessageDialog(null, ex);
         }
    }//GEN-LAST:event_jBtnSearchActionPerformed

    private void jbtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenuActionPerformed
        Menu food = new Menu();
        food.setVisible(true);
    }//GEN-LAST:event_jbtnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catering_Mgnt_Sys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catering_Mgnt_Sys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catering_Mgnt_Sys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catering_Mgnt_Sys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catering_Mgnt_Sys().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnMenu;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JLabel jlabel7;
    private javax.swing.JTextField jtxtCid;
    private javax.swing.JTextField jtxtDate;
    private javax.swing.JTextField jtxtEname;
    private javax.swing.JTextField jtxtFood;
    private javax.swing.JTextField jtxtIno;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPhone;
    private javax.swing.JTextField jtxtQuantity;
    private javax.swing.JTextField jtxtSid;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtaddr;
    // End of variables declaration//GEN-END:variables
}
